# Padding
window_padding_width 8

# Font
font_family      JetBrainsMono Nerd Font Propo
bold_font        JetBrainsMono Nerd Font Propo Bold
italic_font      JetBrainsMono Nerd Font Propo Italic
bold_italic_font JetBrainsMono Nerd Font Propo Bold Italic
font_size        11.0

# Opacity & blur
background_opacity      0.75
background_blur         32

# Backgrounds
background              #1A1510
selection_background    #3A2E20

# Foregrounds
foreground              #E8DFC8
selection_foreground    #E8DFC8

# Cursor
cursor                  #C8961E
cursor_text_color       #1A1510

# URL
url_color               #6A94B8

# Black
color0                  #1A1510
color8                  #3A2E20

# Red
color1                  #A83428
color9                  #D45A44

# Green
color2                  #3A6B46
color10                 #5A9468

# Yellow
color3                  #A07418
color11                 #C8961E

# Blue
color4                  #345678
color12                 #6A94B8

# Magenta
color5                  #614468
color13                 #9478A0

# Cyan
color6                  #2A6060
color14                 #448888

# White
color7                  #C4B896
color15                 #E8DFC8
