# COLORS
$color_active_border   = rgba(3456788C) rgba(2A60608C) 45deg
$color_inactive_border = rgba(231C148C)
$color_shadow          = rgba(3A1A0A66)

# BORDERS
$gaps_in     = 2
$gaps_out    = 4
$border_size = 2

# DECOR
$rounding       = 0
$rounding_power = 0

$active_opacity   = 1.0
$inactive_opacity = 1.0

$shadow_enabled      = false
$shadow_range        = 12
$shadow_render_power = 3

$blur_enabled   = true
$blur_size      = 5
$blur_passes    = 3
$blur_xray      = true
$blur_vibrancy  = 0.2100
