###############
# ENVIRONMENT #
###############

env = ELECTRON_OZONE_PLATFORM_HINT, wayland
env = XCURSOR_THEME, Bibata-Modern-Ice
env = HYPRCURSOR_THEME, Bibata-Modern-Ice
env = XCURSOR_SIZE,22
env = HYPRCURSOR_SIZE,22
