############
# PROGRAMS #
############

$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun

# Custom scripts
$themePicker = ~/dotfiles/theme-picker.sh
$wallpaperPicker = ~/dotfiles/wallpaper-picker.sh
