############
# PROGRAMS #
############

$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun

# Custom scripts
$themePicker = ~/.config/lucky-scripts/theme-picker.sh
$wallpaperPicker = ~/.config/lucky-scripts/wallpaper-picker.sh
