##########################
# WINDOWS AND WORKSPACES #
##########################

# workspace = 1, monitor:DP-3, default:true
# workspace = 2, monitor:HDMI-A-1, default:true
# workspace = 3, monitor:DP-3, default:true

windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

layerrule {
    name = waybar_blur
    ignore_alpha = 0
    blur = on
    match:namespace = waybar
}

layerrule {
    name = rofi_blur
    ignore_alpha = 0
    blur = on
    match:namespace = rofi
}
